name: CI

on:
  push:
    branches: [ main, develop, v2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Skip linting for now due to existing code issues
    # - name: Run ESLint
    #   run: npm run lint:ci --if-present

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Build Extension
      run: npm run compile-production

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Build Package
      run: npm run package

    - name: Upload Extension Package
      uses: actions/upload-artifact@v4
      with:
        name: vscode-extension-${{ github.sha }}
        path: '*.vsix'
        retention-days: 30
